on:
  workflow_dispatch:

jobs:
  install:
    runs-on: macos-14
    strategy:
      fail-fast: false
      matrix:
        python:
          - '3.8'
          - '3.9'
          - '3.10'
          - '3.11'
          - '3.12'
        secretflow:
          - name: secretflow
            version: 1.5.0b0
          - name: secretflow
            version: 1.5.0.dev20240321
          - name: secretflow
            version: 1.5.0.dev20240304
          - name: secretflow
            version: 1.4.0b0
          - name: secretflow
            version: 1.4.0.dev20240116
          - name: secretflow
            version: 1.3.0b0
          - name: secretflow-lite
            version: 1.5.0b0
          - name: secretflow-lite
            version: 1.5.0.dev20240321
          - name: secretflow-lite
            version: 1.5.0.dev20240304
          - name: secretflow-lite
            version: 1.4.0b0
          - name: secretflow-lite
            version: 1.4.0.dev20240116
          - name: secretflow-lite
            version: 1.3.0b0

    steps:
      - uses: mamba-org/setup-micromamba@v1
        with:
          environment-name: test
          create-args: >-
            python=${{ matrix.python }}

      - run: |
          python -m pip install "${{ matrix.secretflow.name }}==${{ matrix.secretflow.version }}"
